### ISSUE TITLE
Change dates/location of conference & CFP

### ISSUE THREAD

**Issue by katialira** [djangocon/2021.djangocon.us#10]
1. Change dates and location
**Expected behavior:**
Online event - October 21-23, 2021
Join us for three days of inspiration, education, and networking opportunities.

Our Call for Proposals is now open

Purple button text: Submit your proposals 
Purple button link: https://www.papercall.io/djangocon-us-2021

**Actual behavior:**
San Diego, CA – October 17-22, 2021
Join us for six days of inspiration, education, and networking opportunities.

Purple button to join mailing list

**Comment by KatherineMichel** [comment]
Looks this is done. Thank you, @katialira!
