### ISSUE TITLE
Discord webhook to announce upcoming talks

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2021.djangocon.us#111]
This is carry over from: https://github.com/djangocon/2021.djangocon.us/pull/87 

Changes proposed in this PR:

- Add requests to the list of requirements
- First draft of a script that iterates through the talks and posts an announcement about the talk upcoming

TODO:
- [x] 1. Create a separate message for 5 minutes to go that doesn't have the YouTube link
- [x] 2. Update the message template to say it's starting now
- [ ] 3. Decide how we want to do the actual scheduling: celery? event loop like tornado? cron job?
- [ ] 4. Iterate over all the talks and test it in Discord
- [ ] 5. Delete all the announcements before we invite anyone in
- [ ] 6. Figure out the best way to link talk URLs to videos without putting the URLs on the public site
   before the talk is actually live
- [ ] 7. Decide what to name the script

To get the webhook URL, go to the talk schedule channel on Discord, click the gear next to the channel name, go to the Integrations tab, click webhooks, then talk schedule bot, then copy webhook URL.

**Comment by shariq1989** [comment]
Are you or anyone else planning on working on this? Otherwise I'm interested in taking this but will probably need some guidance.
