### ISSUE TITLE
Discord preview for talks is still showing 2020 San Diego

### ISSUE THREAD

**Issue by drewbrew** [djangocon/2021.djangocon.us#135]
**Expected behavior:**
Preview image for a talk shows 2021 online

**Actual behavior:**
![image](https://user-images.githubusercontent.com/7773256/137585331-9d0cf490-14ea-47a0-b1f1-626de95bcc27.png)

Kati's talk is missing a preview entirely:
![image](https://user-images.githubusercontent.com/7773256/137585348-bcdd7630-134c-4ae1-92ee-1301b4a7c252.png)

**Steps to repeat behavior:**

- Link to one of the talks in Discord

Is there a script I need to run to regenerate these?

**Comment by jefftriplett** [comment]
@drewbrew I will do a quick verification but I think we are going to have to append something to our image urls (?date=...) to get around Discord's caching.

**Comment by drewbrew** [comment]
Nice work @jefftriplett!
