### ISSUE TITLE
Update "Speaking at Djangocon US"

### ISSUE THREAD

**Issue by williln** [djangocon/2021.djangocon.us#23]
**Data to update**

- [ ] Reflect that CFP is open. Add link to Papercall and the CFP deadline 
- [ ] Update the dates 
- [ ] Confirm whether speakers will pre-record or will livestream 
- [ ] Confirm whether we're still doing a "deep dive" section 
- [ ] Copy for Spanish track -- and should that copy be in both English and Spanish? 
- [ ] Confirm whether we're still doing lightning talks 
- [ ] Remove travel assistance section

**Comment by drewbrew** [comment]
I posted these in Slack, but I'll post here as well so they don't get lost in scrollback:

> Are speakers pre-recording or livestreaming, or do we know yet?

I think it’s better for everyone involved (captioners, AV platform, etc) if we do pre-recorded as much as possible. Adam confirmed that pre-recorded talks are preferred

> Are we still doing a “deep dive” section?

I’d like to if we get enough good talks for it.

> Are we still doing lightning talks?

I don’t see why not, although it’s a bit hard to get Kojo around the world quickly enough to physically remind speakers that their time is running out

> What should I say about our Spanish track?

Asked the comms team for input here
